openapi: 3.0.3
info:
  title: title
  description: description
  version: 0.0.0
components:
  schemas: {}
paths:
  /debug:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: status
          required: false
        - schema:
            type: number
          in: query
          name: id
          required: false
        - schema:
            type: string
          in: header
          name: x-request-id
          required: false
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
servers:
  - url: http://localhost:4000
    description: ローカル環境
  - url: http://localhost:4000
    description: 開発環境
  - url: http://localhost:4000
    description: ステージング環境
  - url: http://localhost:4000
    description: 本番環境
